### PR TITLE
Update tak-md5checksum.txt

### PR DESCRIPTION
**Pull request by KubaMiszcz**
checksum from https://tak.gov/products/tak-server

### CODE REVIEW

**Comment by AlexWinder** [comment]
Have you tested this with the current Docker environment? Looking at the changelog for 4.10 on TPC it appears as though the minimum requirement is now Java 17 and so this suggests that the Dockerfiles will also need to be updated.

**Comment by KubaMiszcz** [comment]
nope, I just added row to table. And yes because I have an isue with it;] describe here:
https://github.com/Cloud-RF/tak-server/issues/43

and here (after update Docekrfile.takserver to use J17):
https://github.com/Cloud-RF/tak-server/issues/37#issuecomment-1858985198

**Comment by KubaMiszcz** [comment]
this changes makes it works with takserver version 4.10 and 5.0

**Comment by wimbime1** [comment]
Hello, I encountered an issue with version tak server 4.7. Therefore, I am attempting to updates to versions 4.10 and 5.0. I have made sure updated the SHA1 and MD5 checksum text files. To ensure the token was correct, I used `sha1sum takserver-docker-X.X-RELEASE-xx.zip` and `md5sum takserver-docker-X.X-RELEASE-xx.zip`, verifying and pasting the provided information into the appropriate text file.

Furthermore, I've updated Java to version 61, which corresponds to Java 17, on my local machine and matches the files in the TAK Server repo. Despite these updates, I'm still encountering the following error:

`Error: LinkageError occurred while loading main class com.bbn.marti.UserManager java.lang.UnsupportedClassVersionError: com/bbn/marti/UserManager has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0`

Could you please advise on how to resolve this issue?

**Comment by wimbime1** [comment]
Thank you for your prompt reply. Based on your response, it appears that the issue may lie within the building stage of Docker, specifically concerning a Java error. Initially, this was something that I assumed. I am aware the 4.10 and 5.0 requires JDK-17. To address this, I have made adjustments to the Dockerfiles, transitioning from JDK-11 to JDK-17 where necessary. Upon review, I identified only two files utilizing JDK-11: the [logo replacement script](https://github.com/Cloud-RF/tak-server/blob/main/scripts/logo-replacement.sh) (line 12) and the [Dockerfile for takserver](https://github.com/Cloud-RF/tak-server/blob/main/docker/amd64/Dockerfile.takserver) (line 1). I attempted to resolve the issue by substituting the JDK version in the Dockerfile with `openjdk:17-jdk-bullseye` and `openjdk:11-jdk`, respectively, and adjusted the logo file from version 11 to 17. However, despite these changes, the error persists. Is there any additional aspect I might have overlooked in troubleshooting this matter?

**Pull request merged**
